export interface Destination {
  id: number
  name: string
  state: string
  type: "Adventurous" | "Calm" | "Cultural" | "Spiritual" | "Beach" | "Historical"
  weather: ("Hot" | "Cold" | "Warm" | "Rainy" | "Mild" | "Snowy")[]
  budget: "₹5K-10K" | "₹8K-15K" | "₹10K-20K" | "₹15K-25K" | "₹20K-30K" | "₹30K-50K" | "₹50K+"
  image: string
  description: string
  tags: string[]
  bestTime: string
  rating: number
  addedBy?: string
  createdAt?: string
}

const defaultDestinations: Destination[] = [
  {
    id: 1,
    name: "Ziro Valley",
    state: "Arunachal Pradesh",
    type: "Adventurous",
    weather: ["Mild", "Cold"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Paddy_fields_at_Ziro%2C_Arunachal_Pradesh.jpg/800px-Paddy_fields_at_Ziro%2C_Arunachal_Pradesh.jpg",
    description: "Terraced rice fields of the Apatani tribe — a hauntingly beautiful valley surrounded by pine-covered hills, part of UNESCO's Tentative World Heritage list.",
    tags: ["tribal-culture", "rice-fields", "UNESCO-tentative"],
    bestTime: "Sep-Nov",
    rating: 4.7,
  },
  {
    id: 2,
    name: "Chopta & Tungnath",
    state: "Uttarakhand",
    type: "Adventurous",
    weather: ["Cold", "Snowy"],
    budget: "₹10K-20K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Tungnath_temple%2C_Chopta%2C_Uttarakhand.jpg/800px-Tungnath_temple%2C_Chopta%2C_Uttarakhand.jpg",
    description: "Alpine meadows and the world's highest Shiva temple — Chandrashila peak offers 360° Himalayan panoramas above the clouds.",
    tags: ["trekking", "spiritual", "alpine"],
    bestTime: "Mar-Jun, Sep-Nov",
    rating: 4.8,
  },
  {
    id: 3,
    name: "Dzukou Valley",
    state: "Nagaland",
    type: "Adventurous",
    weather: ["Mild", "Cold"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Dzukou_Valley_Nagaland.jpg/800px-Dzukou_Valley_Nagaland.jpg",
    description: "A pristine Himalayan valley that erupts with rare Dzukou lilies in summer. The 2-day trek delivers otherworldly green sweeping vistas.",
    tags: ["trekking", "wildflowers", "camping"],
    bestTime: "Jun-Sep",
    rating: 4.6,
  },
  {
    id: 4,
    name: "Spiti Valley",
    state: "Himachal Pradesh",
    type: "Adventurous",
    weather: ["Cold", "Snowy"],
    budget: "₹15K-25K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Key_monastery_%2851874557615%29.jpg/800px-Key_monastery_%2851874557615%29.jpg",
    description: "A cold desert at 12,500 ft with Key Monastery perched on a cliff. Ancient Buddhist villages, snow leopards, and the world's highest post office.",
    tags: ["offroad", "monastery", "high-altitude"],
    bestTime: "Jun-Sep",
    rating: 4.9,
  },
  {
    id: 5,
    name: "Sandakphu",
    state: "West Bengal",
    type: "Adventurous",
    weather: ["Cold", "Mild"],
    budget: "₹10K-20K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Sandakphu.jpg/800px-Sandakphu.jpg",
    description: "The highest peak in West Bengal showing 4 of the world's 5 highest mountains — Everest, Kangchenjunga, Lhotse, and Makalu.",
    tags: ["trekking", "himalayan-views", "rhododendron"],
    bestTime: "Apr-May, Oct-Nov",
    rating: 4.7,
  },
  {
    id: 6,
    name: "Munsiyari",
    state: "Uttarakhand",
    type: "Adventurous",
    weather: ["Cold", "Snowy"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Panchachuli_peak_from_Munsiyari.jpg/800px-Panchachuli_peak_from_Munsiyari.jpg",
    description: "Gateway to several high-altitude treks with jaw-dropping views of the five Panchachuli peaks. The last trading post on the ancient Silk Route.",
    tags: ["trekking", "glaciers", "remote"],
    bestTime: "Apr-Jun, Sep-Nov",
    rating: 4.6,
  },
  {
    id: 7,
    name: "Majuli Island",
    state: "Assam",
    type: "Calm",
    weather: ["Warm", "Mild"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Majuli_river_island_Assam_India.jpg/800px-Majuli_river_island_Assam_India.jpg",
    description: "The world's largest river island in the Brahmaputra — a sanctuary of Vaishnavite Satras, mask-making traditions, and extraordinary sunsets.",
    tags: ["river-island", "culture", "sunsets"],
    bestTime: "Nov-Mar",
    rating: 4.5,
  },
  {
    id: 8,
    name: "Gokarna",
    state: "Karnataka",
    type: "Calm",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Om_Beach%2C_Gokarna%2C_Karnataka%2C_India.jpg/800px-Om_Beach%2C_Gokarna%2C_Karnataka%2C_India.jpg",
    description: "A sacred temple town with Om Beach shaped like the Om symbol — far quieter than Goa with the same turquoise waters and sea cliffs.",
    tags: ["beach", "temple", "peaceful"],
    bestTime: "Oct-Mar",
    rating: 4.6,
  },
  {
    id: 9,
    name: "Tawang",
    state: "Arunachal Pradesh",
    type: "Calm",
    weather: ["Cold", "Mild"],
    budget: "₹10K-20K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Exterior_view_of_the_Tawang_Monastery.jpg/800px-Exterior_view_of_the_Tawang_Monastery.jpg",
    description: "India's largest Buddhist monastery at 10,000 ft, surrounded by glacial lakes, rhododendron forests, and cloud-draped peaks near the Bhutan border.",
    tags: ["monastery", "glacial-lakes", "tranquil"],
    bestTime: "Mar-Oct",
    rating: 4.8,
  },
  {
    id: 10,
    name: "Coorg (Kodagu)",
    state: "Karnataka",
    type: "Calm",
    weather: ["Rainy", "Mild"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Abbey_Falls%2C_Madikeri%2C_Coorg.jpg/800px-Abbey_Falls%2C_Madikeri%2C_Coorg.jpg",
    description: "Scotland of India — coffee and cardamom estates draped in mist, Abbey Falls roaring through the forest, and Kodava warrior hospitality.",
    tags: ["coffee-estates", "waterfalls", "misty"],
    bestTime: "Oct-Mar",
    rating: 4.7,
  },
  {
    id: 11,
    name: "Mawlynnong",
    state: "Meghalaya",
    type: "Calm",
    weather: ["Rainy", "Mild"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Living_Root_Bridge_in_Mawlynnong.jpg/800px-Living_Root_Bridge_in_Mawlynnong.jpg",
    description: "Asia's cleanest village, with living root bridges woven over centuries by the Khasi people — a community forest so pristine it shames cities.",
    tags: ["cleanest-village", "root-bridges", "community"],
    bestTime: "Oct-Mar",
    rating: 4.6,
  },
  {
    id: 12,
    name: "Khajjiar",
    state: "Himachal Pradesh",
    type: "Calm",
    weather: ["Cold", "Mild"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Khajjiar_lake_%28Khajjiar%2C_India%29.jpg/800px-Khajjiar_lake_%28Khajjiar%2C_India%29.jpg",
    description: "India's own Mini Switzerland — a circular lake meadow surrounded by dense cedar forests and the snow-capped Dhauladhar range above Dalhousie.",
    tags: ["meadow", "cedar-forest", "snow-views"],
    bestTime: "Apr-Jun",
    rating: 4.5,
  },
  {
    id: 13,
    name: "Hampi",
    state: "Karnataka",
    type: "Cultural",
    weather: ["Hot", "Warm"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Virupaksha_Temple_and_Bazar%2C_Hampi%2C_Karnataka.JPG/800px-Virupaksha_Temple_and_Bazar%2C_Hampi%2C_Karnataka.JPG",
    description: "A UNESCO World Heritage Site — ruined capital of the Vijayanagara Empire scattered across surreal boulder landscapes. Every stone tells a 500-year story.",
    tags: ["UNESCO", "ruins", "architecture"],
    bestTime: "Oct-Feb",
    rating: 4.9,
  },
  {
    id: 14,
    name: "Orchha",
    state: "Madhya Pradesh",
    type: "Cultural",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Orchha_Fort_and_temples.jpg/800px-Orchha_Fort_and_temples.jpg",
    description: "A forgotten medieval city where 17th-century cenotaphs line the Betwa river and Bundela palaces stand un-renovated — time frozen in amber.",
    tags: ["medieval", "cenotaphs", "fort"],
    bestTime: "Oct-Mar",
    rating: 4.7,
  },
  {
    id: 15,
    name: "Pattadakal",
    state: "Karnataka",
    type: "Cultural",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Pattadakal_temple_complex.jpg/800px-Pattadakal_temple_complex.jpg",
    description: "UNESCO-listed ensemble of 8th-century Chalukya temples that uniquely fuse northern Nagara and southern Dravida architectural styles in one site.",
    tags: ["UNESCO", "temples", "chalukya"],
    bestTime: "Oct-Mar",
    rating: 4.6,
  },
  {
    id: 16,
    name: "Bishnupur",
    state: "West Bengal",
    type: "Cultural",
    weather: ["Warm", "Mild"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Bishnupur_Ras_mancha%2C_West_Bengal.jpg/800px-Bishnupur_Ras_mancha%2C_West_Bengal.jpg",
    description: "Terracotta temples of the Malla kings — Bengal's best-kept cultural secret where Bishnupuri silk weaving and Dhrupad classical music were born.",
    tags: ["terracotta-temples", "silk", "music"],
    bestTime: "Oct-Mar",
    rating: 4.5,
  },
  {
    id: 17,
    name: "Chettinad",
    state: "Tamil Nadu",
    type: "Cultural",
    weather: ["Hot", "Warm"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Chettinad_house.jpg/800px-Chettinad_house.jpg",
    description: "A region of palatial mansions built with Burmese teak and Italian marble by merchant princes, and a spice-heavy cuisine that changed world cooking.",
    tags: ["mansions", "cuisine", "heritage"],
    bestTime: "Nov-Mar",
    rating: 4.7,
  },
  {
    id: 18,
    name: "Mandu",
    state: "Madhya Pradesh",
    type: "Cultural",
    weather: ["Warm", "Rainy"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Jahaz_Mahal%2C_Mandu%2C_M.P.jpg/800px-Jahaz_Mahal%2C_Mandu%2C_M.P.jpg",
    description: "A hilltop fortress city with the ship-shaped Jahaz Mahal and legendary love story of Baz Bahadur and Rani Roopmati — monsoon turns it magical.",
    tags: ["fortress", "afghan-architecture", "romance"],
    bestTime: "Jul-Mar",
    rating: 4.6,
  },
  {
    id: 19,
    name: "Varanasi Hidden Ghats",
    state: "Uttar Pradesh",
    type: "Spiritual",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Varanasi%2C_India_%2822906469774%29.jpg/800px-Varanasi%2C_India_%2822906469774%29.jpg",
    description: "Beyond Dashashwamedh — explore Harishchandra Ghat at 4am, Asi Ghat at sunrise, and the 84 ghats where daily rituals unfold without tourists.",
    tags: ["ghats", "aarti", "ancient"],
    bestTime: "Oct-Mar",
    rating: 4.8,
  },
  {
    id: 20,
    name: "Omkareshwar",
    state: "Madhya Pradesh",
    type: "Spiritual",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Omkareshwar_temple.jpg/800px-Omkareshwar_temple.jpg",
    description: "A sacred island shaped like the Om symbol at the Narmada-Kaveri confluence, home to one of the 12 Jyotirlingas — one of India's most profound pilgrimage sites.",
    tags: ["jyotirlinga", "narmada", "island-temple"],
    bestTime: "Oct-Mar",
    rating: 4.7,
  },
  {
    id: 21,
    name: "Spituk Monastery",
    state: "Ladakh",
    type: "Spiritual",
    weather: ["Cold", "Snowy"],
    budget: "₹15K-25K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Spituk_Gompa%2C_Ladakh.jpg/800px-Spituk_Gompa%2C_Ladakh.jpg",
    description: "Yellow Hat monastery perched dramatically above the Indus Valley with its fierce Kali idol revealed only once a year during the Gustor festival.",
    tags: ["monastery", "tantric", "festival"],
    bestTime: "Jun-Sep",
    rating: 4.8,
  },
  {
    id: 22,
    name: "Gupteswar Caves",
    state: "Odisha",
    type: "Spiritual",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Gupteswar_Shiv_Temple%2C_Jeypore.jpg/800px-Gupteswar_Shiv_Temple%2C_Jeypore.jpg",
    description: "Sacred cave shrine with a naturally-formed Shiva linga deep within limestone caves, located beside the roaring Machkund waterfall in tribal Odisha.",
    tags: ["cave-shrine", "waterfall", "tribal-region"],
    bestTime: "Oct-Mar",
    rating: 4.5,
  },
  {
    id: 23,
    name: "Kamakhya Temple",
    state: "Assam",
    type: "Spiritual",
    weather: ["Warm", "Rainy"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Kamakhya_Temple%2C_Guwahati.jpg/800px-Kamakhya_Temple%2C_Guwahati.jpg",
    description: "One of 51 Shakti Peethas on Nilachal Hill — the Kamakhya complex has lesser-known satellite temples to the 10 Mahavidyas, and hosts the Ambubachi Mela.",
    tags: ["shakti-peetha", "tantric", "goddess"],
    bestTime: "Oct-Mar",
    rating: 4.6,
  },
  {
    id: 24,
    name: "Somnath Temple",
    state: "Gujarat",
    type: "Spiritual",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Somnath_temple_Gujarat.jpg/800px-Somnath_temple_Gujarat.jpg",
    description: "The first Jyotirlinga rebuilt 17 times after invasions — the Bhalka Tirth where Lord Krishna was wounded and the Triveni Sangam are rarely explored by tourists.",
    tags: ["jyotirlinga", "krishna", "sea-temple"],
    bestTime: "Oct-Mar",
    rating: 4.7,
  },
  {
    id: 25,
    name: "Havelock Island",
    state: "Andaman & Nicobar",
    type: "Beach",
    weather: ["Warm", "Hot"],
    budget: "₹20K-30K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Radhanagar_beach.jpg/800px-Radhanagar_beach.jpg",
    description: "Radhanagar Beach — Asia's best beach — with bioluminescent plankton at night, elephant snorkeling, and coral so vibrant it looks hand-painted.",
    tags: ["snorkeling", "bioluminescence", "pristine"],
    bestTime: "Oct-May",
    rating: 4.9,
  },
  {
    id: 26,
    name: "Varkala",
    state: "Kerala",
    type: "Beach",
    weather: ["Warm", "Hot"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Varkala_beach%2C_Kerala.jpg/800px-Varkala_beach%2C_Kerala.jpg",
    description: "Red laterite cliffs towering above the Arabian Sea with natural freshwater springs flowing onto the beach below — geologically unique in all of India.",
    tags: ["cliff-beach", "yoga", "ayurveda"],
    bestTime: "Nov-Mar",
    rating: 4.7,
  },
  {
    id: 27,
    name: "Tarkarli",
    state: "Maharashtra",
    type: "Beach",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Karli_river_meeting_Arabian_sea_Tarkarli.jpg/800px-Karli_river_meeting_Arabian_sea_Tarkarli.jpg",
    description: "Where the Karli river meets the Arabian sea — Maharashtra's most untouched beach with crystal-clear waters perfect for snorkeling and glass-bottom boats.",
    tags: ["snorkeling", "river-meets-sea", "peaceful"],
    bestTime: "Oct-May",
    rating: 4.6,
  },
  {
    id: 28,
    name: "Agonda Beach",
    state: "Goa",
    type: "Beach",
    weather: ["Warm", "Hot"],
    budget: "₹8K-15K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Agonda_beach_Goa.jpg/800px-Agonda_beach_Goa.jpg",
    description: "Goa's most serene beach — the anti-Baga. A nesting site for Olive Ridley turtles with minimal crowds, stunning sunsets, and fishing village life.",
    tags: ["turtle-nesting", "serene", "sunset"],
    bestTime: "Nov-Mar",
    rating: 4.7,
  },
  {
    id: 29,
    name: "Bangaram Atoll",
    state: "Lakshadweep",
    type: "Beach",
    weather: ["Warm", "Hot"],
    budget: "₹30K-50K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Bangaram_island.jpg/800px-Bangaram_island.jpg",
    description: "An uninhabited coral atoll in the Arabian Sea with fluorescent lagoons. Only one eco-resort exists. Untouched reefs make this India's finest diving destination.",
    tags: ["coral-atoll", "diving", "uninhabited"],
    bestTime: "Oct-May",
    rating: 5.0,
  },
  {
    id: 30,
    name: "Mandarmani",
    state: "West Bengal",
    type: "Beach",
    weather: ["Warm", "Mild"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Mandarmani_sea_beach.jpg/800px-Mandarmani_sea_beach.jpg",
    description: "Bengal's longest motorable beach at 13 km — lined with red crabs at dawn, fishing villages, and seafood shacks. A true alternative to Goa's crowds.",
    tags: ["red-crabs", "long-beach", "fishing"],
    bestTime: "Oct-Mar",
    rating: 4.4,
  },
  {
    id: 31,
    name: "Lothal",
    state: "Gujarat",
    type: "Historical",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Lothal_dockyard.jpg/800px-Lothal_dockyard.jpg",
    description: "One of the oldest planned cities on Earth — a 4,500-year-old Indus Valley port city with the world's first tidal dock and a grid-planned street layout.",
    tags: ["indus-valley", "ancient-port", "archaeology"],
    bestTime: "Oct-Mar",
    rating: 4.6,
  },
  {
    id: 32,
    name: "Mandu Historical",
    state: "Madhya Pradesh",
    type: "Historical",
    weather: ["Warm", "Rainy"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Jahaz_Mahal%2C_Mandu%2C_M.P.jpg/800px-Jahaz_Mahal%2C_Mandu%2C_M.P.jpg",
    description: "A spectacular 12th-16th century hilltop fortress city with Afghan-Mughal architecture — the ship-shaped Jahaz Mahal hosts a fleet of rooms built for the harem.",
    tags: ["fortress", "mughal", "ruins"],
    bestTime: "Jul-Mar",
    rating: 4.7,
  },
  {
    id: 33,
    name: "Chitradurga Fort",
    state: "Karnataka",
    type: "Historical",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Chitradurga_fort2.jpg/800px-Chitradurga_fort2.jpg",
    description: "The Stone Fortress — seven layers of concentric granite walls built by successive dynasties over 500 years, with 19 temples and 4 secret gateways.",
    tags: ["fort", "seven-walls", "dynasties"],
    bestTime: "Oct-Mar",
    rating: 4.6,
  },
  {
    id: 34,
    name: "Srirangapatna",
    state: "Karnataka",
    type: "Historical",
    weather: ["Warm", "Hot"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Ranganathaswamy_Temple%2C_Srirangapatna.jpg/800px-Ranganathaswamy_Temple%2C_Srirangapatna.jpg",
    description: "Tipu Sultan's island capital on the Kaveri river — his summer palace, dungeons, mosque, and the exact spot of his legendary last stand in 1799.",
    tags: ["tipu-sultan", "island-fort", "colonial"],
    bestTime: "Oct-Mar",
    rating: 4.5,
  },
  {
    id: 35,
    name: "Dholavira",
    state: "Gujarat",
    type: "Historical",
    weather: ["Hot", "Warm"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Dholavira_excavation_site.jpg/800px-Dholavira_excavation_site.jpg",
    description: "A UNESCO-listed Harappan city in the Rann of Kutch — only site with a large Indus script inscription, and a 5,000-year-old water conservation marvel.",
    tags: ["UNESCO", "harappan", "water-system"],
    bestTime: "Oct-Feb",
    rating: 4.7,
  },
  {
    id: 36,
    name: "Bishnupur Temples",
    state: "West Bengal",
    type: "Historical",
    weather: ["Warm", "Mild"],
    budget: "₹5K-10K",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Bishnupur_Ras_mancha%2C_West_Bengal.jpg/800px-Bishnupur_Ras_mancha%2C_West_Bengal.jpg",
    description: "17th-century Malla kingdom temples built entirely of terracotta bricks, depicting Mahabharata and Ramayana scenes in intricate folk art carvings.",
    tags: ["terracotta", "malla-kingdom", "folk-art"],
    bestTime: "Oct-Mar",
    rating: 4.5,
  },
]

export function getDestinations(): Destination[] {
  if (typeof window === "undefined") return defaultDestinations

  // Always return default destinations on the explore page
  // User-added destinations are stored separately for the add-destination page
  return defaultDestinations
}

export function addDestination(destination: Omit<Destination, "id" | "createdAt">): Destination {
  const destinations = getDestinations()
  const newDestination: Destination = {
    ...destination,
    id: Math.max(...destinations.map((d) => d.id), 0) + 1,
    createdAt: new Date().toISOString(),
  }
  destinations.unshift(newDestination)
  localStorage.setItem("destinations", JSON.stringify(destinations))
  return newDestination
}

export function getDestinationById(id: number): Destination | undefined {
  const destinations = getDestinations()
  return destinations.find((d) => d.id === id)
}
